version: "3"
services:
  auth-db:
    image: postgres
    container_name: auth_db
    restart: always
    environment:
      - POSTGRES_DB=auth_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  
  product-db:
    image: postgres
    container_name: product_db
    restart: always
    environment:
      - POSTGRES_DB=product_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5433:5432
  
  sales-db:
    image: mongo
    container_name: sales_db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    ports:
      - 27017:27017
  
  sales-rabit:
    image: rabbitmq:3-management
    container_name: sales_rabit
    ports:
      - 5672:5672
      - 25676:25676
      - 15672:15672